apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: bio-data-svc # Change it on your own repo-name
      docker:
        buildArgs:
          CI_JOB_TOKEN: "{{.CI_JOB_TOKEN}}"

#profiles:
#- name: dev
#  deploy:
#   helm:
#     releases:
#       - name: bio-data-svc # Change it on your own repo-name
#         setValueTemplates:
#           image.repository: "{{.IMAGE_REPO_verificator_svc}}" # Change <backend> on your own repo-name
#           image.tag: "{{.IMAGE_TAG_verificator_svc}}" # Change <backend> on your own repo-name
#         namespace: dev # Change it on your own namespace
#         createNamespace: true
#         chartPath: ./bio-data-svc-chart # Change it on your own path to helm chart
#         valuesFiles:
#           - ./bio-data-svc-chart/values.yaml # Change it on your own path to helm chart values.yaml file
#         skipBuildDependencies: true
#     flags:
#       upgrade:
#         - -i
#  portForward:
#   - resourceType: deployment
#     resourceName: bio-data-svc # Change it on your own name in Chart.yaml
#     port: 8000
#     localPort: 8000

# - name: stage
#   deploy:
#     helm:
#       releases:
#         - name: backend # Change it on your own repo-name
#           setValueTemplates:
#             image.repository: "{{.REGISTRY}}/{{.SERVICE}}"
#             image.tag: "{{.CI_COMMIT_SHA}}"
#           namespace: stage # Change it on your own namespace
#           createNamespace: true
#           chartPath: ./backend # Change it on your own path to helm chart
#           valuesFiles:
#             - ./backend/values.yaml # Change it on your own path to helm chart values.yaml file
#           skipBuildDependencies: true
#       flags:
#         upgrade:
#           - -i

# - name: prod
#   deploy:
#     helm:
#       releases:
#         - name: backend # Change it on your own repo-name
#           setValueTemplates:
#             image.repository: "{{.REGISTRY}}/{{.SERVICE}}"
#             image.tag: "{{.CI_COMMIT_TAG}}"
#           namespace: prod # Change it on your own namespace
#           createNamespace: true
#           chartPath: ./backend # Change it on your own path to helm chart
#           valuesFiles:
#             - ./backend/values.yaml # Change it on your own path to helm chart values.yaml file
#           skipBuildDependencies: true
#       flags:
#         upgrade:
#           - -i